export const CHANGE_TITLE = "CHANGE_TITLE";
export const CHANGE_SCHEDULE = "CHANGE_SCHEDULE";
export const CHANGE_START_TIME = "CHANGE_START_TIME";
export const CHANGE_END_TIME = "CHANGE_END_TIME";
export const ADD_TO_DAYS_LIST = "ADD_TO_DAYS_LIST";
export const REMOVE_FROM_DAYS_LIST = "REMOVE_FROM_DAYS_LIST";
